experiment_name: ptbxl_super_adapt_jepa
dataset_name: ptbxl
task: diagnosis_adapt
data_config: FILIP-data.md
data_root: data/ptbxl_super_class/
stage1_checkpoint: outputs/filip/ablation_vit_large_jepa/checkpoints/best.pt

model:
  vision_encoder: openai/clip-vit-large-patch14
  image_size: 224
  patch_size: 14
  use_feature_alignment: true
  feature_topk: 8
  feature_align_dim: 256
  diagnosis_from_features: false
  use_adapters: true
  adapter_type: lora
  num_diagnosis: 5

loss:
  diagnosis_loss_weight: 1.0
  feature_consistency_weight: 0
  use_asl: true

training:
  batch_size: 32
  backbone_lr: 3.0e-5
  head_lr: 3.0e-4
  epochs: 10
  unfreeze_last_n_layers: 2
  mixed_precision: true
  report_to: wandb
